version: "3"
services:
  api:
    build: .
    container_name: frontend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    command: sh -c "yarn install && yarn run serve"