version: "3"
services:
  api:
    build: .
    container_name: mercadopago_api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    command: sh -c "yarn install && yarn run start:dev"